apiVersion: v1
kind: Service  
metadata:
  name: httpd-rv64-service  
spec:
  selector:    
    app: httpd-rv64
  ports:  
  - protocol: TCP  
    port: 80 
    targetPort: 80
    nodePort: 30081 
  type: NodePort